### ISSUE TITLE
Get back from image preview panel to original source image in Omero

### ISSUE THREAD

**Issue by abhamacher** [will-moore/parade-crossfilter#17]
Hi Will,

in the image preview panel there should be a possibility to click on the image to get back to Omero and the original source image viewer. There is now on top a "Open with" option, but it basically doesn't show me any option. Tested with Firefox, Chrome and Edge on Windows.

**Comment by will-moore** [comment]
What do you see at the top of the page when you have items selected? Anything like this screenshot?
Do you have an `Image` column in your table?
Any errors in the dev-tools Console?

<img width="389" alt="Screenshot 2021-12-15 at 07 10 50" src="https://user-images.githubusercontent.com/900055/146140600-b1e5d65d-a781-405f-8460-165158ee59c4.png">

**Comment by abhamacher** [comment]
Hi Will,

no I didn't have a "Image" column in the data at that point. Now I tried to add it and get a fancy new populate metadata error. It doesn't take long anymore, then I will have probably experienced all possible error code ;-)

`omero_metadata.populate.MetadataError: Well Column and Image Column cannot be resolved at the same time. Pick one.`

So I cannot have "well" and "image" information together in the data, is that right? Do I really have to remove the well column? can't omero-metadata just pick the information that is most granular?

Thanks, Anna

**Comment by abhamacher** [comment]
And here's another one after removing the "well" column:

`Traceback (most recent call last):
  File "./script", line 124, in populate_metadata
    ctx.parse_from_handle(data)
AttributeError: 'ParsingContext' object has no attribute 'parse_from_handle'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./script", line 181, in <module>
    run_script()
  File "./script", line 173, in run_script
    message = populate_metadata(client, conn, script_params)
  File "./script", line 128, in populate_metadata
    ctx.preprocess_from_handle(data_for_preprocessing)
  File "/mnt/data/OMERO.venv/server_venv3/lib64/python3.6/site-packages/omero_metadata/populate.py", line 1069, in preprocess_from_handle
    self.preprocess_data(reader)
  File "/mnt/data/OMERO.venv/server_venv3/lib64/python3.6/site-packages/omero_metadata/populate.py", line 1143, in preprocess_data
    column, original_value, row)
  File "/mnt/data/OMERO.venv/server_venv3/lib64/python3.6/site-packages/omero_metadata/populate.py", line 447, in resolve
    return images_by_id[int(value)].id.val
ValueError: invalid literal for int() with base 10: 'Index.idx.xml [Well 1 Field 1]'
Exception ignored in: <bound method _TemporaryFileCloser.__del__ of <tempfile._TemporaryFileCloser object at 0x7f73116adef0>>
Traceback (most recent call last):
  File "/usr/lib64/python3.6/tempfile.py", line 452, in __del__
    self.close()
  File "/usr/lib64/python3.6/tempfile.py", line 448, in close
    unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/home/omero-server/omero/tmp/omero_omero-server/778/populate_roivh6hy8p_dir/tmp7xj24myd'
Exception ignored in: <bound method _TemporaryFileCloser.__del__ of <tempfile._TemporaryFileCloser object at 0x7f73116ad208>>
Traceback (most recent call last):
  File "/usr/lib64/python3.6/tempfile.py", line 452, in __del__
    self.close()
  File "/usr/lib64/python3.6/tempfile.py", line 448, in close
    unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/home/omero-server/omero/tmp/omero_omero-server/778/populate_roivh6hy8p_dir/tmp2br1bod3'`

So I was obviously thinking the image mapping is name based, but it's obviously not. Which image ID is omero-metadata expecting at that point? Please don't tell me it's the internal Omero image ID.

**Comment by will-moore** [comment]
Ah, apologies - I didn't mean to break your `omero-metadata` workflow!

I should be able to fix it so that parade doesn't need Image IDs.
They're mostly just used for showing Images in the right panel (which you won't have been seeing?) and for the Links.
But I should be able to link to Well instead if Image isn't there.
And for a Preview of the Well, I could probably load the contained Images (if a single Well is selected). If a small number of Wells are loaded then I could show the first Image in each Well.
Not sure what to show if many Wells are selected.

**Comment by abhamacher** [comment]
Hi Will,

no worries, I've build a KNIME workflow to generate  a `populate metadata`-ready to use csv file out of a Cellprofiler image result file, which makes it fairly easy to adapt the output in terms of adding of removing columns. 

Still I have the feeling of being lost in the omero-metadata universe. For now it seems to me the following works:

1. adding metadata to a plate object only with "well" column (can be multiple rows per image, but may **not** contain "image" or "plate" column)
2. adding metadata to a screen object only with "plate" and "well" column for usage in parade-crossfilter (but the bulk annotation csv needs to be downloaded first and reuploaded to the screen again)

It is a bit uncomfortable that I can not use the same csv-file for both operations. Not even to mention the download and re-upload step... And when I do not have the image mapping, I can not really link the image analysis data per image to a specific image. And I still would like to test also the mask export of the segmented cells in Cellprofiler to import them as ROIs into Omero. But this would only make sense if the image mapping is given.

Can't we use this field as mapping value?
![imagedesc](https://user-images.githubusercontent.com/61734239/146248088-d8bff3fe-8f32-420f-ac61-1547936de14b.PNG)

This is something that I can pretty easily integrate into my KNIME workflow to be derived from the plate data itself without getting Omero image IDs beforehand.

**Comment by will-moore** [comment]
The omero metadata workflow has quite limited flexibility, but I think we need to move this discussion to an issue there https://github.com/ome/omero-metadata (or image.sc), so that the relevant people can get involved. Can you paste there an example CSV snippet that you want it to handle? Similar to the before and after examples on the omero-metadata README page.
In KNIME you're not connected to OMERO are you?

I think I've got the "Open Wells in webclient / iviewer" working, so this issue should be fixed without needing Image IDs.

As for the download and re-upload of the CSV, I've just added the ability to open OMERO.table files directly, so you won't have to do that for much longer. Will try to get a release out soon...

**Comment by abhamacher** [comment]
Hi Will,

I tested the "Open with" Menu and it works fine! I can open one well in iviewer and also multiple in webclient, which highlights the previously selected in the plate layout. That's great. Thank you!  I tested this based on data from an OMERO.tables object, so this works fine too.

And you're right I will open a separate issue for the omero-metadata import topic.
