### ISSUE TITLE
Issue with updated Django version

### ISSUE THREAD

**Issue by abhamacher** [will-moore/parade-crossfilter#26]
Hi @will-moore,

as recommended by Josh I upgraded omero-web today together with omero-py, etc. This included an update of Django to version 3.2.12. Unfortunately the omero-web service is now unable to start on our testserver, moaning about something in the parade-crossfilter plugin:

systemctl status omero-web.service
● omero-web.service - OMERO.web
   Loaded: loaded (/etc/systemd/system/omero-web.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Sun 2022-04-03 17:00:19 CEST; 4s ago
  Process: 27246 ExecStart=/mnt/data/OMERO.venv/web_venv3/bin/omero web start (code=exited, status=1/FAILURE)
 Main PID: 1258 (code=exited, status=0/SUCCESS)

Apr 03 17:00:19 omero-cai-test omero[27246]: __import__(urlmodule)
Apr 03 17:00:19 omero-cai-test omero[27246]: File "/mnt/data/OMERO.venv/web_venv3/lib64/python3.6/site-packages/parade_crossfilter/urls.py", line 20, in <module>
Apr 03 17:00:19 omero-cai-test omero[27246]: from . import views
Apr 03 17:00:19 omero-cai-test omero[27246]: File "/mnt/data/OMERO.venv/web_venv3/lib64/python3.6/site-packages/parade_crossfilter/views.py", line 27, in <module>
**Apr 03 17:00:19 omero-cai-test omero[27246]: from django.core.urlresolvers import reverse
Apr 03 17:00:19 omero-cai-test omero[27246]: ModuleNotFoundError: No module named 'django.core.urlresolvers'**
Apr 03 17:00:19 omero-cai-test systemd[1]: omero-web.service: control process exited, code=exited status=1
Apr 03 17:00:19 omero-cai-test systemd[1]: Failed to start OMERO.web.
Apr 03 17:00:19 omero-cai-test systemd[1]: Unit omero-web.service entered failed state.
Apr 03 17:00:19 omero-cai-test systemd[1]: omero-web.service failed.

I guess this is something you might need to adapt in the code?

Regads, Anna

**Comment by will-moore** [comment]
Hi Anna,
 Apologies, I hadn't updated for the latest omero-web.
But I just pushed a fix as `parade-crossfilter 0.0.5` to pypi. That should get things working again.
 Regards,
  Will

**Comment by abhamacher** [comment]
Thanks for your fast response, works fine now!
